export { default as Home } from './Home/Home'
export { default as Jobs } from './Jobs/Jobs'
export { default as About } from './About/About'
export { default as Contact } from './Contact/Contact'
export { default as Services } from './Services/Services'
