export { default as PageDescription } from './PageDescription/PageDescription'
export { default as PageHeader } from './PageHeader/PageHeader'
export { default as PageGalery } from './PageGalery/PageGalery'
export { default as CardData } from './CardData/CardData'
export { default as Prices } from './Prices/Prices'
